services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    ports:
      - "3307:3306"
    networks:
      - student-network
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: student-app
    ports:
      - "8080:8080"
    networks:
      - student-network
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/students?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:

networks:
  student-network:
    driver: bridge
