# ---------------- Spring Boot Deployment ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sconfigsecretcruddemo-deployment
  labels:
    app: k8sconfigsecretcruddemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8sconfigsecretcruddemo
  template:
    metadata:
      labels:
        app: k8sconfigsecretcruddemo
    spec:
      containers:
        - name: k8sconfigsecretcruddemo
          image: k8sconfigsecretcruddemo-image:1.0   # <-- यहाँ अपना image नाम दें That name was given at the time of creation docker image.
          imagePullPolicy: Never #Kubernetes docker hub registry से image pull करने की कोशिश नहीं करेगा
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST # Setting host name from mysql-config-map.yml file
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: host
            - name: DB_NAME # Setting DB name from mysql-config-map.yml file
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: dbName
            - name: SPRING_DATASOURCE_USERNAME # Setting DB username from mysql-secrets.yml
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD # Setting DB password from mysql-secrets.yml
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$(DB_HOST):3306/$(DB_NAME)?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

---

# ---------------- Spring Boot Service ----------------
apiVersion: v1
kind: Service
metadata:
  name: k8sconfigsecretcruddemo-service
  labels:
    app: k8sconfigsecretcruddemo
spec:
  type: NodePort       # चाहें तो ClusterIP भी कर सकते हैं
  selector:
    app: k8sconfigsecretcruddemo
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 32080   # optional: Kubernetes चुने तो इसे हटा दें
